export const TEXT_RESOURCES = {
    ja: {
        titleSubtitle: 'Think Fast. Judge Faster.',
        selectDifficulty: '難易度を選択',
        difficulty: {
            beginner: '初級',
            intermediate: '中級',
            advanced: '上級',
            master: '超級',
        },
        cards: '枚',
        options: '設定',
        timeUp: 'タイムアップ！',
        score: 'スコア',
        retry: 'もう一度',
        backToTitle: 'タイトルへ戻る',
        paused: '一時停止',
        resume: '再開',
        quit: '終了',
        pauseBtn: '一時停止 (ESC)',
        statScore: 'スコア',
        statCorrect: '正解',
        statMiss: 'ミス',
        timer: '残り時間',

        // Options Modal
        optionsTitle: '設定',
        audio: 'オーディオ',
        bgmVolume: 'BGM音量',
        sfxVolume: '効果音音量',
        visual: 'ビジュアル',
        screenShake: '画面の揺れ',
        flashEffects: 'フラッシュ効果',
        language: '言語',
        close: '閉じる',
        mute: 'ミュート',
        muted: 'ミュート中',
        on: 'ON',
        off: 'OFF',

        // Credits
        credits: 'クレジット',
        creditsTitle: 'クレジット',
        sections: {
            music: '音楽',
            sfx: '効果音',
            programming: 'プログラミング',
            design: 'デザイン',
            specialThanks: 'スペシャルサンクス',
        },
    },
    en: {
        titleSubtitle: 'Think Fast. Judge Faster.',
        selectDifficulty: 'SELECT DIFFICULTY',
        difficulty: {
            beginner: 'BEGINNER',
            intermediate: 'INTERMEDIATE',
            advanced: 'ADVANCED',
            master: 'MASTER',
        },
        cards: 'CARDS',
        options: 'OPTIONS',
        timeUp: 'TIME UP!',
        score: 'SCORE',
        retry: 'RETRY',
        backToTitle: 'BACK TO TITLE',
        paused: 'PAUSED',
        resume: 'RESUME',
        quit: 'QUIT',
        pauseBtn: 'PAUSE (ESC)',
        statScore: 'SCORE',
        statCorrect: 'CORRECT',
        statMiss: 'MISS',
        timer: 'TIME',

        // Options Modal
        optionsTitle: 'OPTIONS',
        audio: 'AUDIO',
        bgmVolume: 'BGM VOLUME',
        sfxVolume: 'SFX VOLUME',
        visual: 'VISUAL',
        screenShake: 'SCREEN SHAKE',
        flashEffects: 'FLASH EFFECTS',
        language: 'LANGUAGE',
        close: 'CLOSE',
        mute: 'MUTE',
        muted: 'MUTED',
        on: 'ON',
        off: 'OFF',

        // Credits
        credits: 'CREDITS',
        creditsTitle: 'CREDITS',
        sections: {
            music: 'MUSIC',
            sfx: 'SOUND EFFECTS',
            programming: 'PROGRAMMING',
            design: 'DESIGN',
            specialThanks: 'SPECIAL THANKS',
        },
    },
};
